### PR TITLE
Work in progress: Histogram

### PR DESCRIPTION
**Pull request by birdstorm**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/96)

### CODE REVIEW

**Comment by zhexuany** [comment]
@birdstorm we need resolve a lot conflicts. Please ping me if PR is ready to review.

**Comment by birdstorm** [comment]
I'm afraid we may need to refactor part of the cmmits to sync with master, I will make it reviewable this weekend.

**Comment by ilovesoup** [comment]
@birdstorm make sure you build necessary index before hand on test cluster and do some test to see if you assigned right cost factors. The real cost factor will be different than in TiDB to achieve good effect.

**Comment by birdstorm** [comment]
@zhexuany @ilovesoup done resolve conflict. (that was huge)

**Comment by zhexuany** [comment]
@birdstorm Awesome Work. Please ping me if PR is ready. 🥇

**Comment by birdstorm** [comment]
@zhexuany ya, it is!

**Comment by birdstorm** [comment]
Just to mention that I did a brutal implementation on original `Comparables`. This PR is likely going to be split into smaller PRs with deeper discussion later.

**Comment by birdstorm** [comment]
Because of too many conflicts against master branch since we switched to DAG, this PR will be redo. 

Closing.

**Pull request closed without merging**
