### PR TITLE
upgrade grpc to 1.7

### PR DESCRIPTION
**Pull request by zhexuany**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/157)

### CODE REVIEW

**Comment by zhexuany** [comment]
@ilovesoup @birdstorm PTAL.

**Comment by zhexuany** [comment]
passed first three TPCH test in our cluster. Should to be to take off.

**Review by ilovesoup — APPROVED** [review]
LGTM

**Comment by ilovesoup** [comment]
resolve https://github.com/pingcap/tikv-client-lib-java/issues/155

**Pull request merged**
