### PR TITLE
fix potential error escape

### PR DESCRIPTION
**Pull request by ilovesoup**
Add throw for a potential exception escape

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/182)

### CODE REVIEW

**Comment by ilovesoup** [comment]
@birdstorm @Novemser PTAL

**Comment by birdstorm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/182)*

**Comment by birdstorm** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/182#-:-L-f-nIoLI5AAPV7d7F5:bnfp4nl)*

**Review by birdstorm — APPROVED** [review]
LGTM

**Pull request merged**
