### PR TITLE
Update pom file

### PR DESCRIPTION
**Pull request by zhexuany**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/168)

### CODE REVIEW

**Review by ilovesoup — APPROVED** [review]
LGTM. But why we need to update plugins?

**Comment by zhexuany** [comment]
I checked this issue https://github.com/pingcap/tikv-client-lib-java/issues/121. And realized that most of plugins have new version available.

**Review by ilovesoup — APPROVED** [review]
LGTM

**Review by ilovesoup — APPROVED** [review]
LGTM

**Pull request merged**
