### PR TITLE
added travis file for ci

### PR DESCRIPTION
**Pull request by zhexuany**

### CODE REVIEW

**Review by ilovesoup — COMMENTED** [review]
Not sure what to do about Travis-ci with maven, but is jar in git repo the only way to do?

**Comment by zhexuany** [comment]
Travis-CI is smarter. If a java project come with `pom.xml`, then travis-ci will use `mvn`. But if a java project come with `mvmw`, travis-ci will use `./mvnw`.  In our case, travis-ci will use `./mvnw`. In such situation, `.mvn` is needed for a runtime environment.  If we do not want  any jar file in repo, then we need delete all `mvnw` files.

**Comment by ilovesoup** [comment]
Any chance use script to download jar before hand? Typically binary files should be kept away from repo.

**Comment by zhexuany** [comment]
@ilovesoup Check out the latest commit. The complaint is caused by `install`  in travis-ci default way. Skipping it and manually install dependency and test on `script` section can bypass this.

**Comment by hongyuanw** [comment]
> mvn install -DskipTests=true 

Maybe we should not skip tests ?

**Comment by zhexuany** [comment]
@yuanwhy Ah, you forget the next line. The first line is for installing dependency. Test is done via `mvn Test -B`.

**Comment by ilovesoup** [comment]
lgtm

**Review by ilovesoup — APPROVED** [review]

**Pull request merged**
