### PR TITLE
added .gitignore file

### PR DESCRIPTION
**Pull request by zhexuany**

### CODE REVIEW

**Comment by zhexuany** [comment]
@ilovesoup @shenli PTAL.

**Comment by ilovesoup** [comment]
Initially it comes with a .gitignore but deleted suggested by @shenli .
I guess it's quite a personalized file which users prefer to have their own.

**Comment by zhexuany** [comment]
@ilovesoup 
people usually assume project come with a .gitignore file when they clone to a dev machine.
I agree with @shenli. .gitignore file is quite personal, but this file also prevent accidentally commit unrelated file in a PR.
Personally, I have at lease three dev environment. It is tedious every time clone it and recreate a .gitignore file for this project.  
Practically, almost every repo has a .gitignore. In my opinion, it would be better that we can add .gitignore file.

**Comment by ilovesoup** [comment]
LGTM

**Review by ilovesoup — APPROVED** [review]

**Pull request merged**
