### PR TITLE
add support to ignore unsupported types

### LINKED ISSUE #136: Should add a switch for user to ignore type unsupported
For now we haven't implemented `enum` and `set` yet, so before they are done we should add a switch for users to ignore unsupported types. It looks ugly to throw an Exception like `Invalid xx flag type`. Throwing `Error: Unsupported Type xx` should be better.

### PR DESCRIPTION
**Pull request by birdstorm**
fix #136

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/208)

### CODE REVIEW

**Comment by birdstorm** [comment]
For dag tests:

Result: Tests run: 7335  Tests succeeded: 3775  Tests failed: 8  Tests skipped: 3552

**Review by Novemser — APPROVED** [review]
LGTM

**Comment by Novemser** [comment]
BTW plz run TPCH tests and put test result here.

**Comment by birdstorm** [comment]
I will submit a new pull request to modify ReadMe, for now this pr is ready.

**Comment by birdstorm** [comment]
Here is TPCH test result:

Result: Tests run: 21  Tests succeeded: 21  Tests failed: 0  Tests skipped: 0

**Pull request merged**
