### PR TITLE
Maxiaoyu/conditon pushdown

### PR DESCRIPTION
**Pull request by ilovesoup**
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tikv-client-lib-java/43)

### CODE REVIEW

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 1 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 2 of 43 files at r1.
Review status: 3 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/pingcap/tikv/Snapshot.java, line 130 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYAhOkww0EmimckokV:-KnYAhOkww0EmimckokW:bp6ck6f) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/Snapshot.java#L130)):*
> ```Java
>     /*
>      * Below method is lower level interface for distributed environment
>      * which avoids calling PD on slave nodes
> ```

Maybe add @param here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 4 of 43 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 5 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/codec/KeyUtils.java, line 38 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYAz6SsdmCsDovZZO-:-KnYAz6SsdmCsDovZZO0:b-o1j5l6) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/codec/KeyUtils.java#L38)):*
> ```Java
>      * Original bytes will be reused if possible
>      * @param key key to encode
>      * @return
> ```

Missing description for return 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 6 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 7 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 8 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 9 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 10 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 11 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 12 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 13 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 14 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 15 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 16 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 17 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Review status: 17 of 43 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java, line 52 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYC6vq_jAz5z_LXUCC:-KnYC6vq_jAz5z_LXUCD:b-lh9i2z) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java#L52)):*
> ```Java
>                        @JsonProperty("index_type")int                indexType,
>                        // This is a fake property and added JsonProperty only to
>                        // to by pass Jackson frameworks's check
> ```

may be "bypass"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 18 of 43 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 19 of 43 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Review status: 19 of 43 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 58 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYCOiJ4dO2xylB2pmA:-KnYCOiJ4dO2xylB2pmB:b6lp3nn) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L58)):*
> ```Java
>     private final List<TiExpr> fields = new ArrayList<>();
>     private final List<TiExpr> where = new ArrayList<>();
>     private final List<TiByItem> groupBys = new ArrayList<>();
> ```

maybe add a TODO here? groupBys here is kinda confusing. Per each query, there will be only one groupBy but multiple expression. I am wondering could we do the following:
~~~
TiByItem groupBy;
groupBy.addExpr(expr);
~~~

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 85 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYCpVQemk6umNK5Fkr:-KnYCpVR05gl03SL7wU2:b-oyom28) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L85)):*
> ```Java
> 
>     public SelectRequest build() {
>         checkArgument(startTs != 0, "timestamp is 0");
> ```

Guard is awesome. We definitely need check this. ;)

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 92 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYDPJp7zl9t8cUgjTN:-KnYDPJp7zl9t8cUgjTO:b-1vk58f) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L92)):*
> ```Java
> 
>         TiTableInfo filteredTable = tableInfo;
>         if (!fields.isEmpty()) {
> ```

Please discard your changes in `build()`. `dev_master` has correct version. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 20 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 21 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 22 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 23 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 24 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 25 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 26 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 27 of 43 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 28 of 43 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/predicates/PredicateUtils.java, line 38 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYEq9GaUpUOm0ey3U3:-KnYEq9GaUpUOm0ey3U4:bx9da9p) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/predicates/PredicateUtils.java#L38)):*
> ```Java
>     }
> 
>     public static List<TiColumnRef> getColumnRefFromExpr(TiExpr expr) {
> ```

add todo here maybe. just get is not elegant. It should be get and merge. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 28 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 29 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 30 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 31 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 32 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 33 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 34 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 35 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 36 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 37 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 38 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 39 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 40 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 41 of 43 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: 42 of 43 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 43 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by ilovesoup** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 58 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYCOiJ4dO2xylB2pmA:-KnYU1UeNpuItmH5YwCx:b-if1wg) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L58)):*
> bypass
will change to group by items

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by ilovesoup** [comment]
Review status: 37 of 44 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/pingcap/tikv/Snapshot.java, line 130 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYAhOkww0EmimckokV:-KnYVXGfZQA0YU_l9-DU:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/Snapshot.java#L130)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

Maybe add @param here
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/codec/KeyUtils.java, line 38 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYAz6SsdmCsDovZZO-:-KnYVZjJDDQQmO-7Sp62:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/codec/KeyUtils.java#L38)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

Missing description for return 
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java, line 52 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYC6vq_jAz5z_LXUCC:-KnYV_MLurfGYVbIrz61:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiIndexInfo.java#L52)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

may be "bypass"
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 58 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYCOiJ4dO2xylB2pmA:-KnYV_tWhnX_qe5j2qeX:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L58)):*
<details><summary><i>Previously, ilovesoup (Soup) wrote…</i></summary><blockquote>

> bypass
will change to group by items
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 85 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYCpVQemk6umNK5Fkr:-KnYVbzGmJJQbR1daEJB:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L85)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

Guard is awesome. We definitely need check this. ;)
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java, line 92 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYDPJp7zl9t8cUgjTN:-KnYVctWB3K3vLWdRrXk:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java#L92)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

Please discard your changes in `build()`. `dev_master` has correct version. 
</blockquote></details>

Done.

---

*[src/main/java/com/pingcap/tikv/predicates/PredicateUtils.java, line 38 at r1](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-KnYEq9GaUpUOm0ey3U3:-KnYVdSysXKlF3O-E49S:b-896fix) ([raw file](https://github.com/pingcap/tikv-client-lib-java/blob/988ab97544e752df057987861c085f38a984a097/src/main/java/com/pingcap/tikv/predicates/PredicateUtils.java#L38)):*
<details><summary><i>Previously, zhexuany (Yang Zhexuan) wrote…</i></summary><blockquote>

add todo here maybe. just get is not elegant. It should be get and merge. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 38 of 44 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 39 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 40 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 41 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 42 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: 43 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43)*

**Comment by zhexuany** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pingcap/tikv-client-lib-java/43#-:-KnYWuWdejW_i2HK_HW9:bnfp4nl)*

**Pull request merged**
